#
# Makefile for the Mellanox device drivers.
#

obj-$(CONFIG_MLX4_CORE) += mlx4/
obj-$(CONFIG_MLX5_CORE) += mlx5/core/
obj-$(CONFIG_MLXSW_CORE) += mlxsw/
obj-$(CONFIG_MLX_ACCEL_CORE) += accelerator/core/
obj-$(CONFIG_MLX_ACCEL_IPSEC) += accelerator/ipsec/
obj-$(CONFIG_MLX_ACCEL_TLS) += accelerator/tls/
obj-$(CONFIG_MLX_ACCEL_TOOLS) += accelerator/tools/
